os: linux
language: node_js
node_js:
  - "node"

stages:
  - build
  - release

jobs:
  include:
  - stage: build
    script:
      - npm run build
  - stage: release
    if: env(TRAVIS_EVENT_TYPE) != cron AND env(TRAVIS_EVENT_TYPE) != pull_request
    script:
      - npm run release
